export const expensesCategoryData = [
    { id: 1, value: "Advance of Expert Fee", label: "Advance of Expert Fee" },
    { id: 2, value: "Appeal Fee", label: "Appeal Fee" },
    { id: 3, value: "BBA Fee", label: "BBA Fee" },
    { id: 4, value: "Built Property Tax", label: "Built Property Tax" },
    { id: 5, value: "Claim Fee", label: "Claim Fee" },
    { id: 6, value: "Clearance NSSF", label: "Clearance NSSF" },
    { id: 7, value: "Company Incorporation Fee", label: "Company Incorporation Fee" },
    { id: 8, value: "Contribution to the Judges Funds", label: "Contribution to the Judges Funds" },
    { id: 9, value: "Court Fee", label: "Court Fee" },
    { id: 10, value: "Deposit Fee", label: "Deposit Fee" },
    { id: 11, value: "Office / Electricity", label: "Office / Electricity" },
    { id: 12, value: "Expert Fee", label: "Expert Fee" },
    { id: 13, value: "External Lawyer Fee", label: "External Lawyer Fee" },
    { id: 14, value: "External Lawyer Legal Opinion Fee", label: "External Lawyer Legal Opinion Fee" },
    { id: 15, value: "Fines", label: "Fines" },
    { id: 16, value: "Travel / Flight", label: "Travel / Flight" },
    { id: 17, value: "Transportation Fee / Fuel", label: "Transportation Fee / Fuel" },
    { id: 18, value: "Travel / Hotel", label: "Travel / Hotel" },
    { id: 19, value: "Income Tax", label: "Income Tax" },
    { id: 20, value: "Office / Internet & Telephone", label: "Office / Internet & Telephone" },
    { id: 21, value: "Office / IT Expenses", label: "Office / IT Expenses" },
    { id: 22, value: "Judgment Fee", label: "Judgment Fee" },
    { id: 23, value: "Lawyers Stamp", label: "Lawyers Stamp" },
    { id: 24, value: "Company Incorporation Fee / Legal Docs", label: "Company Incorporation Fee / Legal Docs" },
    { id: 25, value: "Travel / Meal", label: "Travel / Meal" },
    { id: 26, value: "Miscellaneous", label: "Miscellaneous" },
    { id: 27, value: "Office", label: "Office" },
    { id: 28, value: "Office / Office Supplies", label: "Office / Office Supplies" },
    { id: 29, value: "Transportation Fee / Parking Fee", label: "Transportation Fee / Parking Fee" },
    { id: 30, value: "Power of Attorney Fee", label: "Power of Attorney Fee" },
    { id: 31, value: "Printing & Copying", label: "Printing & Copying" },
    { id: 32, value: "Proportional Tax", label: "Proportional Tax" },
    { id: 33, value: "Real Estate Fee", label: "Real Estate Fee" },
    { id: 34, value: "Registration Fee", label: "Registration Fee" },
    { id: 35, value: "Renewal Fee", label: "Renewal Fee" },
    { id: 36, value: "Office / Rent", label: "Office / Rent" },
    { id: 37, value: "Signification", label: "Signification" },
    { id: 38, value: "Stamp duties", label: "Stamp duties" },
    { id: 39, value: "Stamp of the Judges Funds", label: "Stamp of the Judges Funds" },
    { id: 40, value: "Transportation Fee / Taxi", label: "Transportation Fee / Taxi" },
    { id: 41, value: "Trade License Fee", label: "Trade License Fee" },
    { id: 42, value: "Transfer Tax", label: "Transfer Tax" },
    { id: 43, value: "Company Incorporation Fee / Translation", label: "Company Incorporation Fee / Translation" },
    { id: 44, value: "Transportation Fee", label: "Transportation Fee" },
    { id: 45, value: "Travel / Transportation Fee", label: "Travel / Transportation Fee" },
    { id: 46, value: "Travel", label: "Travel" }
];
