export const practiceAreaOptions = [
    { id: 1, value: 'administrative', lable: 'Administrative' },
    { id: 2, value: 'arbitration', lable: 'Arbitration' },
    { id: 3, value: 'civil', lable: 'Civil' },
    { id: 4, value: 'commercial', lable: 'Commercial' },
    { id: 5, value: 'company formation', lable: 'Company Formation' },
    { id: 6, value: 'criminal', lable: 'Criminal' },
    { id: 7, value: 'data protection and privacy', lable: 'Data Protection and Privacy' },
    { id: 8, value: 'due diligence', lable: 'Due Diligence' },
    { id: 9, value: 'family', lable: 'Family' },
    { id: 10, value: 'insurance', lable: 'Insurance' },
    { id: 11, value: 'employment', lable: 'Employment' },
    { id: 12, value: 'legal opinion', lable: 'Legal Opinion' },
    { id: 13, value: 'merger and acquisition', lable: 'Merger and Acquisition' },
    { id: 14, value: 'tax', lable: 'Tax' },
    { id: 15, value: 'setting dispute', lable: 'Setting Dispute' },
    { id: 16, value: 'wills', lable: 'Wills' },
    { id: 17, value: 'trademark', lable: 'Trademark' },
    { id: 18, value: 'bankruptcy', lable: 'Bankruptcy' },
    { id: 19, value: 'immigration', lable: 'Immigration' },
]